sudo: false
language: python
python:
# Sphinx requires at least Python 3.3 to run.
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - source .travis_ssh_setup.sh
  - source .travis_install.sh
install:
  - pip install -e .
  - pip install -r docs/requirements.txt
before_script:
  - python -c 'from pwn import *; print(pwnlib.term.term_mode)' NOTERM
  - python -c 'from pwn import *; print(pwnlib.term.term_mode)' NOTERM
  - python -c 'from pwn import *; print(pwnlib.term.term_mode)' NOTERM
  - python -c 'from pwn import *; print(pwnlib.term.term_mode)' NOTERM
script: PWNLIB_NOTERM=1 make -C docs doctest

